name: test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          [
            native-tls,
            rustls,
            async-std,
            tokio,
            async-std-async-native-tls,
            tokio-async-native-tls,
            async-std-rustls,
            tokio-rustls,
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Clippy
        run: cargo clippy --package suppaftp --features ${{ matrix.features }} -- -Dwarnings

      - name: Run tests with coverage
        run: cargo llvm-cov --no-fail-fast --no-default-features --features ${{ matrix.features }} --workspace --lcov --output-path lcov-${{ matrix.features }}.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          file: lcov-${{ matrix.features }}.info

  wait-for-coverage:
    name: Wait for coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Wait for coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
